version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-20.04
  tools: {}

python:
  install:
    - method: setuptools
      path: .
