version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-23.11"

conda:
  environment: docs/environment.yml

python:
  install:
    - method: setuptools
      path: .
