steps:
  - name: ":python:"
    command: |
        pwd
        ls
        pip install --progress-bar off pytest 
        pip install --progress-bar off --upgrade jax jaxlib==0.1.63+cuda112 -f https://storage.googleapis.com/jax-releases/jax_releases.html
        pip install --progress-bar off -e .
        python -c "import mpi4jax; print(mpi4jax.__version__)"
        python -c "import jax; print(jax.devices())"
        pytest .
        mpirun --allow-run-as-root -np 4 pytest .
    plugins:
      - docker-compose#v3.0.3:
          run: testing-environment
