name: mpi4jax-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.7
  - numpy
  - mpi4py
  - cython
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
    # JAX is behind on conda-forge, seems like pip is better supported
    - jax[cpu]
