name: mpi4jax-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - openmpi-mpicc
  - mpi4py<4
  - numpy
  - cython
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
    # JAX is behind on conda-forge, seems like pip is better supported
    - jax[cpu]
